### PR TITLE
698 - Bug in CSV Upload

### LINKED ISSUE #698: Bugs in the mission csv upload?
## **Changes:**

Fix CSV upload code so that it works

## **Requirements:**

- [ ] Fix functions in `ScuntMissionServices` to add the csv upload functionality
- [ ] Look at how the PDF receipt is being sent from frontend to backend for a better idea on how to handle file uploads

### PR DESCRIPTION
**Pull request by Tanushanth**
### **Issue:**

Closes #698 

### **Accomplishments:**

- Changes 'Items' key to 'Missions' in mapping parameter for parseCsvString within `ScuntMissionsDashboard.jsx`

### **Visuals:** 

image

### **Expected Behavior:**

- Head to `/scunt-missions-dashboard` with a leader account to upload a mission CSV of the following form:  #,Mission,Category,Points,Hidden,Judging Station?
- Should be able to preview and upload missions at this page

### **Testing Steps:**

Steps required to get expected behavior.

- With a leader account that has necessary scunt mission permissions (ex create), head to the mission panel under the scunt dropdown in the `/profile` page
- Once at `/scunt-missions-dashboard`, head to the third tab (upload missions), and create a csv with missions with the following headers: #,Mission,Category,Points,Hidden,Judging Station?
- Upload the csv, and click preview CSV, this should display the items in the table
- After clicking this, the Upload Missions button will be functional

### **Complications:**

- Was not originally working for random reasons (length is undefined, etc). The Key in the mapping parameter in `scuntMissionsDashboard.jsx` just needed to be changed from Items to Missions (to match `scuntMissionServices.jsx`)

### **Resources:**

Any additional resources used outside this in issue.

### CODE REVIEW

File: client/src/state/scuntMissions/saga.jsx [hunk 1]
```diff
@@ -33,13 +33,13 @@ export function* getScuntMissionsSaga({ payload: { showHidden, setSnackbar } })
...
+export function* createMultipleMissionsSaga({ payload: { file, array, setSnackbar } }) {
   const { axios } = useAxios();
   try {
     yield put(getScuntMissionsStart());
     const formData = new FormData();
     formData.append('missions', file);
-    const result = yield call(axios.post, 'scunt-missions/bulk', formData, {
+    const result = yield call(axios.post, 'scunt-missions/bulk', formData, array, {
       headers: { 'Content-Type': 'multipart/form-data' },
     });
```
Comment (Freeassassin) [inline client/src/state/scuntMissions/saga.jsx]:
```suggestion
    const result = yield call(axios.post, 'scunt-missions/bulk', array, {
      headers: { 'Content-Type': 'multipart/form-data' },
    });
```

File: server/src/controllers/ScuntMissionController.js [hunk 2]
```diff
@@ -73,8 +73,10 @@ const ScuntMissionController = {
   },
   async createMultipleMissions(req, res, next) {
     try {
+      console.log(req.array)
+      console.log("^ contorller")
       const missions = await ScuntMissionServices.createMultipleMissions(
-        req.file.buffer.toString(),
+        req.file.buffer.toString(), req.array
```
Comment (Freeassassin) [inline server/src/controllers/ScuntMissionController.js]:
```suggestion
        req.file.buffer.toString(), req.body.array
```
